name: synclayer
description: A local-first sync SDK for Flutter with offline support, automatic conflict resolution, and real-time synchronization.
version: 1.0.0
homepage: https://sdk.hostspica.com/flutter/synclayer
repository: https://github.com/hostspicaindia/synclayer
issue_tracker: https://github.com/hostspicaindia/synclayer/issues
documentation: https://sdk.hostspica.com/docs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  dio: ^5.9.1
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.5
  uuid: ^4.5.2
  crypto: ^3.0.3
  appwrite: ^21.3.0
  cloud_firestore: ^6.1.2
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_lints: ^3.0.2
