name: synclayer
description: Local-first sync engine for Flutter with offline support, delta sync, encryption, custom conflict resolvers, and real-time synchronization.
version: 1.6.0
homepage: https://sdk.hostspica.com/flutter/synclayer
repository: https://github.com/hostspicaindia/synclayer
issue_tracker: https://github.com/hostspicaindia/synclayer/issues
documentation: https://sdk.hostspica.com/docs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  dio: ^5.9.1
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.5
  uuid: ^4.5.2
  crypto: ^3.0.3
  encrypt: ^5.0.3
  # Database adapters (optional - include only what you need)
  cloud_firestore: ^6.1.2
  supabase_flutter: ^2.12.0
  appwrite: ^21.3.0
  postgres: ^3.0.0
  mysql1: ^0.20.0
  mongo_dart: ^0.10.0
  sqflite: ^2.4.1
  redis: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_lints: ^3.0.2
